# Generated by Django 4.2.4 on 2023-08-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stages', '0001_initial'),
        ('Adminstrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('adminstration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminstrations.adminstrations')),
                ('stage', models.ManyToManyField(to='Stages.stages')),
            ],
        ),
    ]
